[versions]
# libraries
annotations = "24.0.1"
slf4j = "2.0.9"

# plugins
dokka = "1.8.20"
kotlin = "1.8.20"
gradleIntelliJPlugin = "1.14.1"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
slf4jApi = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
